version: '3.3'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    ports:
      - 8080:8000
    env_file:
      - ./.env.prod


volumes:
  static_volume:
