version: '3.3'

services:
  web-jeremie:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 80
    ports:
      - 80:8080
    env_file:
      - ./.env.prod
    depends_on:
      - db

  web-jeremie:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 80
    ports:
      - 80:8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8081:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
