apiVersion: v1
kind: Service
metadata:
  name: {{ include "jeremie.fullname" . }}
  labels:
    {{- include "jeremie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: 8000
  selector:
    {{- include "jeremie.selectorLabels" . | nindent 4 }}
